language: node_js
node_js:
  - "lts/*"
install:
  - pip install --upgrade --user awscli
script:
  - cd website-client/
  - npm run build
deploy:
  - pwd
  - cd dist/
  - |
    function upload_to() {
      if [ -z "$1" ];
        echo "Error: No bucket name provided."
        exit 1
      fi
      for FILE in $(ls); do
        aws s3api put-object --bucket "$1" --key "$FILE" --body "$FILE"
      done
    }
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if [ "$TRAVIS_BRANCH" = "develop" ]; then
        upload_to dev.seankrail.com || exit 2
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        upload_to staging.seankrail.com || exit 3
      elif [[ "$TRAVIS_TAG" = release-* ]]; then
        upload_to prod.seankrail.com || exit 4
      fi
    fi
