name: Build PR Changes

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          sudo npm uninstall -g parcel-bundler
          yarn
          yarn format-check
          # builds silently fail with exit code 129
          # not sure who the culprit is; everything builds fine locally
          # after a few failed builds, it finally builds successfully
          yarn build || yarn build || yarn build || yarn build || yarn build

      - name: Create 404.html
        run: |
          cd dist/
          ln -s index.html 404.html

      - name: Create git history file
        run: |
          git log > dist/log
