name: Build PR Changes

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          sudo npm uninstall -g parcel-bundler
          yarn
          yarn lint-check
          yarn format-check
          # builds silently fail with exit code 129
          # not sure who the culprit is; everything builds fine locally
          # after a few failed builds, it finally builds successfully
          yarn build || yarn build || yarn build || yarn build || yarn build

      - name: Create 404.html
        run : |
          cd dist/
          ln -s index.html 404.html

      - name: Create git history file
        run: |
          git log > dist/log
