name: Build PR Changes

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm style:check
          pnpm build

      - name: Create 404.html redirect
        run: |
          cd dist/
          ln -s index.html 404.html

      - name: Create git history file
        run: |
          git log > dist/log
