name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: public
          fqdn: krail.dev
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
