name: Deploy GitHub Pages
on:
  push:
    branches:
      - mainline
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          yarn
          yarn lint-check
          yarn format-check
          yarn build
      - name: Create 404.html
        run : |
          cd dist/
          ln -s index.html 404.html
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
          fqdn: krail.dev
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
