name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Build
        run: |
          pnpm install
          pnpm format:check
          pnpm build
      - name: Create 404.html and resume redirects
        run: |
          cd dist/
          echo 'include: [".well-known"]' > _config.yml
          ln -s index.html 404.html
          # ln -s seankrail-resume.pdf resume.pdf
      - name: Create git history file
        run: |
          git log > dist/log
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          include-hidden-files: true
          path: dist/
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
