name: Deploy GitHub Pages
on:
  push:
    branches:
      - mainline
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          sudo npm uninstall -g parcel-bundler
          yarn
          yarn lint-check
          yarn format-check
          # builds silently fail with exit code 129
          # not sure what is the culprit; everything builds fine locally
          # after a few failed builds, it finally builds successfully
          yarn build || yarn build || yarn build || yarn build || yarn build
      - name: Create 404.html
        run : |
          cd dist/
          ln -s index.html 404.html
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
          fqdn: seankrail.dev
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
