name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          sudo npm uninstall -g parcel-bundler
          yarn
          yarn format-check
          # builds silently fail with exit code 129
          # not sure who the culprit is; everything builds fine locally
          # after a few failed builds, it finally builds successfully
          yarn build || yarn build || yarn build || yarn build || yarn build

      - name: Create 404.html and other redirects
        run: |
          cd dist/
          ln -s index.html 404.html
          ln -s seankrail-resume.pdf resume.pdf

      - name: Create git history file
        run: |
          git log > dist/log

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          fqdn: seankrail.dev
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
