name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          sudo npm uninstall -g parcel-bundler
          yarn
          yarn lint-check
          yarn format-check
          # builds silently fail with exit code 129
          # not sure who the culprit is; everything builds fine locally
          # after a few failed builds, it finally builds successfully
          yarn build || yarn build || yarn build || yarn build || yarn build

      - name: Create 404.html and other redirects
        run : |
          cd dist/
          ln -s index.html 404.html
          ln -s seankrail-resume.pdf resume.pdf

      - name: Create git history file
        run: |
          git log > dist/log

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          fqdn: seankrail.dev
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
